Feat/aur auto release
animo/agent-cli pull request #158
Opened 2022-04-08 19:19 UTC by morrieinmaas

Github action/pipeline to automate releasing new versions to AUR

2022-04-08 19:21 UTC, blu3beri approved these changes

2022-04-08 19:21 UTC, blu3beri commented on .github/workflows/aur-release.yml
> +          # use the rsa key for git
We should use ed25519 ;)

2022-04-08 19:22 UTC, blu3beri commented
Looks great! Just fix the commits, remove unrelated ones, and we can merge.

2022-04-08 19:22 UTC, morrieinmaas commented on .github/workflows/aur-release.yml
> +          # use the rsa key for git
alright i'll change that

2022-04-08 19:23 UTC, morrieinmaas commented
thanks. well it's branched off the other one - thought that'd be merged already. I'll get rid of the junk ;)

2022-04-08 19:24 UTC, blu3beri requested changes

2022-04-08 19:24 UTC, blu3beri commented on .github/workflows/aur-release.yml
> +      - name: Gather data and rewrite ruby file
Ruby?

2022-04-08 19:24 UTC, blu3beri commented on .github/workflows/aur-release.yml
> +    name: release brew
Brew

2022-04-08 19:24 UTC, blu3beri commented on .github/workflows/aur-release.yml
> +  release-brew:
Brew

2022-04-08 19:29 UTC, morrieinmaas commented on .github/workflows/aur-release.yml
> +      - name: Gather data and rewrite ruby file
lol - sorry about that should really call it a day now 😅

2022-04-08 19:30 UTC, morrieinmaas commented
The other PR is good to go. Wait with this please, I wanna test it a bit more after some sleep

2022-04-08 20:17 UTC, blu3beri commented on .github/workflows/aur-release.yml
> +          # use the rsa key for git
Haha its okay. Was more a joke because we use that for signatures in AFJ :).

2022-04-09 09:58 UTC, blu3beri commented
You can mention me when you are done. If everything works it looks good to me :).

2022-04-09 10:01 UTC, morrieinmaas commented
tested all the steps from local and it that works. However there is always a chance if container of gh action behaving slightly different. let me trigger this ofr the current build and see if it works

2022-04-11 07:28 UTC, morrieinmaas commented
Just FYI @blu3beri (as you probably have noticed already) it's not yet working using the GH actions runner. I'm working on it. Just trying to debug this - felling like a monkey with a drum right now

2022-04-25 09:02 UTC, morrieinmaas commented
@blu3beri I'm stuck atm. The cert permissions on the runner give me errors although I change them. Not quite sure how to solve this. Will have another look.

2022-04-29 13:28 UTC, morrieinmaas commented
alrighty @blu3beri testest in [fork](https://github.com/morrieinmaas/agent-cli/actions/runs/2245609058) and works finally. thx for your help

2022-04-29 13:48 UTC, blu3beri approved these changes

2022-04-29 13:49 UTC, merged