feat(aca-py): oob receive and create invitation
animo/agent-cli pull request #213
Opened 2022-09-05 12:49 UTC by morrieinmaas

closes #211

2022-09-05 14:06 UTC, blu3beri requested changes

2022-09-05 14:08 UTC, morrieinmaas commented on crates/agent/src/modules/oob.rs
> +    pub invi_msg_id: String,
we get this back in the payload - eg:
```json
{
  "created_at": "2021-12-31T23:59:59Z",
  "invi_msg_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "invitation": {
    "@id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "@type": "https://didcomm.org/my-family/1.0/my-message-type",
    "handshake_protocols": [
      "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/didexchange/1.0"
    ],
    "label": "Bob",
    "requests~attach": [
      {
        "@id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "byte_count": 1234,
        "data": {
          "base64": "ey4uLn0=",
          "json": {
            "sample": "content"
          },
          "jws": {
            "header": {
              "kid": "did:sov:LjgpST2rjsoxYegQDRm7EL#keys-4"
            },
            "protected": "ey4uLn0",
            "signature": "ey4uLn0",
            "signatures": [
              {
                "header": {
                  "kid": "did:sov:LjgpST2rjsoxYegQDRm7EL#keys-4"
                },
                "protected": "ey4uLn0",
                "signature": "ey4uLn0"
              }
            ]
          },
          "links": [
            "https://link.to/data"
          ],
          "sha256": "617a48c7c8afe0521efdc03e5bb0ad9e655893e6b4b51f0e794d70fba132aacb"
        },
        "description": "view from doorway, facing east, with lights off",
        "filename": "IMG1092348.png",
        "lastmod_time": "2021-12-31T23:59:59Z",
        "mime-type": "image/png"
      }
    ],
    "services": [
      {
        "did": "WgWxqztrNooG92RXvxSTWv",
        "id": "string",
        "recipientKeys": [
          "did:key:z6MkpTHR8VNsBxYAAWHut2Geadd9jSwuBV8xRoAnwWsdvktH"
        ],
        "routingKeys": [
          "did:key:z6MkpTHR8VNsBxYAAWHut2Geadd9jSwuBV8xRoAnwWsdvktH"
        ],
        "serviceEndpoint": "http://192.168.56.101:8020",
        "type": "string"
      },
      "did:sov:WgWxqztrNooG92RXvxSTWv"
    ]
  },
  "invitation_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "invitation_url": "https://example.com/endpoint?c_i=eyJAdHlwZSI6ICIuLi4iLCAiLi4uIjogIi4uLiJ9XX0=",
  "oob_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "state": "await_response",
  "trace": true,
  "updated_at": "2021-12-31T23:59:59Z"
}
```

2022-09-05 14:08 UTC, morrieinmaas commented on crates/agent/src/modules/oob.rs
> +    pub invi_msg_id: String,
what would you rename it to?

2022-09-05 14:09 UTC, morrieinmaas commented on crates/cli/src/modules/oob.rs
> +    print!("{decoded_str}");
oops

2022-09-05 14:10 UTC, morrieinmaas commented on crates/cli/src/modules/oob.rs
> +    print!("{decoded_str}");
advanced debug ;P

2022-09-05 14:25 UTC, morrieinmaas commented on crates/agent/src/modules/oob.rs
> +pub struct OobConnectionCreateInvitationOptions {
??

2022-09-05 16:13 UTC, blu3beri commented on crates/agent/src/modules/oob.rs
> +pub struct OobConnectionCreateInvitationOptions {
This structure is specific to the `cli` package and not the `agent`. I think we do this everywhere but I will have to refactor this out.

2022-09-06 08:29 UTC, morrieinmaas commented on crates/agent/src/modules/oob.rs
> +pub struct OobConnectionCreateInvitationOptions {
ah ok. Then I can take it out here already

2022-09-06 08:32 UTC, blu3beri commented on crates/agent/src/modules/oob.rs
> +pub struct OobConnectionCreateInvitationOptions {
Ah id rather just do everything at once. You can leave it here.

2022-09-06 08:48 UTC, morrieinmaas commented on crates/agent/src/modules/oob.rs
> +pub struct OobConnectionCreateInvitationOptions {
alright then - keep your secrets...

can we merge then?

2022-09-06 16:31 UTC, blu3beri approved these changes

2022-09-06 16:31 UTC, merged