feat: webhooks listener
animo/agent-cli pull request #215
Opened 2022-09-07 09:05 UTC by morrieinmaas

wip

This works but needs some tlc

Signed-off-by: Moriarty <moritz@animo.id>

2022-09-07 12:19 UTC, morrieinmaas commented
closes #214

2022-09-07 12:20 UTC, morrieinmaas commented
Probably should add this to the docs as well @blu3beri - will do when no other changes required.

2022-09-07 12:36 UTC, blu3beri requested changes
I like the addition, very useful and @karimStekelenburg will be happy! However the implementation needs some changes. 

1. Webhooks should not be a crate
2. Environment should be retrieved from the webhookcommand but from the agent-cli.
3. The `listen` function should use the logger crate for printing.
4. The `listen` function MUST not panic. 
5. `listen` function needs some refactoring but that can be done in a separate PR.

2022-09-07 12:36 UTC, blu3beri commented on Cargo.toml
> +webhooks = { path = "./crates/webhooks" }
Don't know how I feel about it being a separate crate. Does not really make sense to me.

2022-09-07 12:36 UTC, blu3beri commented on crates/cli/src/help_strings.rs
> +            Self::WebhooksEnvironment => "The environment from the config to use for listening to webhooks",
This should not be added here. the core `cli` package manages state here. It should just be passed in like

```
agent-cli --environment="foo" listen
```

and not

```
agent-cli listen --environment="foo"
```

2022-09-07 12:36 UTC, blu3beri commented on crates/cli/src/modules/webhooks.rs
> +    match &options.commands {
This should not be done here and is done by the base `agent-cli` and not command specific.

2022-09-07 12:36 UTC, blu3beri commented on crates/webhooks/src/lib.rs
> +            _ => { panic!() }
`unreachable!()` is preferred here.

2022-09-07 12:36 UTC, blu3beri commented on crates/webhooks/src/lib.rs
> +    let (mut socket, _response) = connect(Url::parse(&listen_url).unwrap()).expect("Can't connect to websocket");    // Write a message containing "Hello, Test!" to the server
All the expects should be removed and transformed into returning in `Result`

2022-09-07 12:36 UTC, blu3beri commented on crates/webhooks/src/lib.rs
> +    println!("Listening on {}\n", listen_url);
Should use the logger crate.

2022-09-07 12:36 UTC, blu3beri commented on crates/webhooks/src/lib.rs
> +        println!("{}{}", ("Received hook:\n").yellow(), to_string_pretty(&parsed).unwrap());
Should use print.

2022-09-07 12:38 UTC, morrieinmaas commented on Cargo.toml
> +webhooks = { path = "./crates/webhooks" }
Where else would you put it?

2022-09-07 12:41 UTC, morrieinmaas commented on Cargo.toml
> +webhooks = { path = "./crates/webhooks" }
just as a module in cli i guess?!

2022-09-07 12:44 UTC, morrieinmaas commented on crates/webhooks/src/lib.rs
> +        println!("{}{}", ("Received hook:\n").yellow(), to_string_pretty(&parsed).unwrap());
could also use the logger here @blu3beri ?

2022-09-07 13:15 UTC, blu3beri commented on Cargo.toml
> +webhooks = { path = "./crates/webhooks" }
yes.

2022-09-07 17:31 UTC, blu3beri requested changes
Good changes, but the `listen` function is not consistent with the other modules or inline with idiomatic Rust.

2022-09-07 17:31 UTC, blu3beri commented on crates/cli/src/modules/webhooks.rs
> +pub fn listen(agent_url: String) -> ! {
I am not a fan of the `!` return in this case.

As I mentioned before, we should return a result so we can handle errors like we are doing in every submodule.

```suggestion
pub fn listen(agent_url: String) -> Result<()> {
```

This makes it very easy to handle errors in a consistent way across all the modules.

Using `unreachable!` and `unwrap` is extremely discouraged and there must be a very good reason for it to be in the codebase.


In this case we should just bubble-up the error and deal it in a general way.

2022-09-07 17:31 UTC, blu3beri commented on crates/cli/src/modules/webhooks.rs
> +        s => s,
This is not correct and will panic below.

Is neither of the cases are met we should return an error and bubble it up.

2022-09-07 17:31 UTC, blu3beri commented on crates/cli/src/modules/webhooks.rs
> +    let (mut socket, _response) = match connect(Url::parse(&listen_url).unwrap()) {
```suggestion
    let (mut socket, _response) = match connect(Url::parse(&listen_url)?) {
```

Likely needs an error conversion to a custom agent-cli error.

2022-09-07 17:31 UTC, blu3beri commented on crates/cli/src/modules/webhooks.rs
> +        Err(e) => {log!("{}", e); unreachable!()}
This should not be done here and the `connect` function just needs another error conversion and be called like `connect(...)?`.

2022-09-07 17:31 UTC, blu3beri commented on crates/cli/src/modules/webhooks.rs
> +        let msg = match socket.read_message() {
Same here. No error case and it should be like this:

```suggestion
        let msg = match socket.read_message()?;
```

2022-09-07 17:31 UTC, blu3beri commented on crates/cli/src/modules/webhooks.rs
> +        let parsed: Value = from_str(&msg).expect("Can't parse to JSON");
no expect.

2022-09-07 17:31 UTC, blu3beri commented on crates/cli/src/modules/webhooks.rs
> +        log!("{}{}\n", ("Received hook:\n").yellow(), to_string_pretty(&parsed).unwrap());
no unwrap.

and a nicer way would be two logs:

```rust
log!("Received hook:\n");
log!("{}", ...);
```

2022-09-07 17:31 UTC, blu3beri commented on crates/cli/src/register.rs
> +                    Commands::Webhooks(_) => {listen(agent.endpoint)},
for convince in patterns just pass a reference to the entire agent. Seems a bit odd to do it differently here.

2022-09-07 17:31 UTC, blu3beri commented on crates/cli/src/modules/webhooks.rs
> +        let msg = match msg {
Same here. `unreachable!`, my fault for recommending it, is an undesirable pattern and should be avoided in cases where we can (like here).

2022-09-07 17:31 UTC, blu3beri commented
@morrieinmaas If you have no time for this I can also apply the fixes myself.

2022-09-07 18:34 UTC, morrieinmaas commented
Thx for all the feedback @blu3beri ! If it's not urgent Id rather do it myself to get some practice in. If it is urgent feel free to go ahead

2022-09-08 06:01 UTC, morrieinmaas commented on crates/cli/src/modules/webhooks.rs
> +        s => s,
hmm I see. Was thinking that there might be a url without prefix in there... But I guess you do have a point here - better to assume the url is wrong altogether

2022-09-08 06:56 UTC, morrieinmaas commented on crates/cli/src/modules/webhooks.rs
> +pub fn listen(agent_url: String) -> ! {
I do get your point - however, wondering whether Result is the right return type cos it just prints to void until ctrl-c so it's more like void or error?! Dunno (*newbie facepalm*)

2022-09-08 07:05 UTC, morrieinmaas commented on crates/cli/src/modules/webhooks.rs
> +pub fn listen(agent_url: String) -> ! {
so not sure how Ok is returned

2022-09-08 07:37 UTC, blu3beri commented on crates/cli/src/modules/webhooks.rs
> +pub fn listen(agent_url: String) -> ! {
Ok(()) should be the last line of your code and will be returned when the loop exits for any reason. `<C-c>` will short-circuit. 

Your `void or error` is exactly what a `Result<()>` means.

return nil, or void on Ok
return Error on Error

2022-09-08 16:58 UTC, morrieinmaas commented
Alright did my best to finish it but there is the return type issue left. Feel free to do the rest and merge if you want as I'm out until Tuesday.

Cheers

2022-09-09 09:13 UTC, blu3beri approved these changes

2022-09-09 09:17 UTC, merged